git add git.sh
git add readme.txt
git add tests.txt
git add vulnerabilities.txt
git add bt_parse.c
git add bt_parse.h
git add constants.h
git add chunk.c
git add chunk.h
git add client.c
git add debug-text.h
git add debug.h
git add debug.c
git add input_buffer.c
git add input_buffer.h
git add Makefile
git add peer.c
git add peer.h
git add peer_run.c
git add peer_run.h
git add runA.sh
git add runB.sh
git add server.c
git add sha.c
git add sha.h
git add spiffy.c
git add spiffy.h
git add structures.h
git add packet_helper.h
git add packet_helper.c
git add process.c
git add process.h
git add process_helper.c
git add process_helper.h
git tag -f checkpoint-2 -m "commit"

